FROM golang:alpine AS builder

ARG VERSION

RUN apk update && apk add --no-cache \
    git \
    curl \
    jq
WORKDIR $GOPATH/src/pkg/app/
COPY . .

WORKDIR $GOPATH/src/pkg/app/web
RUN go get -d -v

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X github.com/sgryczan/klutch/common.Version=${VERSION}" -o /go/bin/web

RUN download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
  jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url') && \
curl -o /usr/local/bin/swagger -L'#' "$download_url" && \
chmod +x /usr/local/bin/swagger

RUN /usr/local/bin/swagger generate spec -o ./swaggerui/swagger.json

FROM alpine

RUN apk update && apk add --no-cache ca-certificates
EXPOSE 8080

COPY --from=builder /go/bin/web /go/bin/web
COPY --from=builder /go/src/pkg/app/web/swaggerui /go/bin/swaggerui
WORKDIR /go/bin

ENTRYPOINT ["./web"]