version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: sgryczan/klutch:web-v0.0.0
    container_name: web
    restart: always
    ports:
      - "80:8080"
    depends_on:
        - redis
        - rabbitmq
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
  task:
    build:
      context: .
      dockerfile: Dockerfile.task
    image: sgryczan/klutch:task-v0.0.0
    container_name: task
    restart: always
    depends_on:
        - redis
        - rabbitmq