FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/pkg/app/
COPY . .

WORKDIR $GOPATH/src/pkg/app/web
RUN go get -d -v

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /go/bin/web

FROM alpine

RUN apk update && apk add --no-cache ca-certificates
EXPOSE 8080

COPY --from=builder /go/bin/web /go/bin/web
COPY --from=builder /go/src/pkg/app/web/swaggerui /go/bin/swaggerui
WORKDIR /go/bin


ENTRYPOINT ["./web"]